Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/mantic64"
    vm1.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/mantic64"
    vm2.vm.network :forwarded_port, guest: 22, host: 2002, id: "ssh"
  end
  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "ubuntu/mantic64"
    vm3.vm.network :forwarded_port, guest: 22, host: 2003, id: "ssh"
  end
  config.vm.define "vm4" do |vm4|
    vm4.vm.box = "ubuntu/mantic64"
    vm4.vm.network :forwarded_port, guest: 22, host: 2004, id: "ssh"
  end
 config.vm.define "vm5" do |vm5|
    vm5.vm.box = "ubuntu/mantic64"
    vm5.vm.network :forwarded_port, guest: 22, host: 2005, id: "ssh"
  end
 config.vm.define "vm6" do |vm6|
    vm6.vm.box = "ubuntu/mantic64"
    vm6.vm.network :forwarded_port, guest: 22, host: 2006, id: "ssh"
  end
 config.vm.define "vm7" do |vm7|
    vm7.vm.box = "ubuntu/mantic64"
    vm7.vm.network :forwarded_port, guest: 22, host: 2007, id: "ssh"
  end
 config.vm.define "vm8" do |vm8|
    vm8.vm.box = "ubuntu/mantic64"
    vm8.vm.network :forwarded_port, guest: 22, host: 2008, id: "ssh"
  end
 config.vm.define "vm9" do |vm9|
   vm9.vm.box = "ubuntu/mantic64"
   vm9.vm.network :forwarded_port, guest: 22, host: 2009, id: "ssh"
  end

  config.vm.network "public_network", bridge: "pub1v142"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "50000"
    vb.cpus = "8"
  end
end

