apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipfwd-bridge
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "ipfwdbr",
    "ipam": {
    }
  }'
