apiVersion: v1
kind: ConfigMap
metadata:
  name: vpp-configmap
  labels:
    app: vpp
    chart: vpp-0.1.0
data:
{{ range $k, $v := .Values.cnf }}
  setup_{{$k}}.gate: |-
    create host-interface name net1
    set int state host-net1 up
  startup_{{$k}}.conf: |-
    unix {
      nodaemon
      interactive
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      startup-config /etc/vpp/setup.gate
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    cpu {
      main-core {{ .main_core }}
      corelist-workers {{ .worker_cores }}
    }

    plugins {
      plugin default { disable }
      plugin ping_plugin.so { enable }
    }
{{ end }}
