---
apiVersion: v1
kind: Namespace
metadata:
  name: cnfspace
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: cnfspace
spec:
  securityContext:
    runAsNonRoot: true

  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
  dnsPolicy: Default
