apiVersion: v2
appVersion: latest
description: The Helm chart for Envoy Gateway
home: https://gateway.envoyproxy.io/
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg
keywords:
- gateway-api
- envoyproxy
- envoy-gateway
- eg
maintainers:
- name: envoy-gateway-steering-committee
  url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
- name: envoy-gateway-maintainers
  url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS
name: gateway-helm
sources:
- https://github.com/envoyproxy/gateway
type: application
version: v0.0.0-latest
