apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csp.fullname" . }}
  labels:
    app: {{ include "csp.name" . }}
    chart: {{ include "csp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "csp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "csp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      {{ range $k, $v := .Values.cnf }}
        - name: {{ $.Chart.Name }}-{{$k}}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          securityContext:
            privileged: {{ $.Values.privileged }}
          resources:
{{ toYaml $.Values.resources | indent 12 }}
          volumeMounts:
          - name: config-volume
            subPath: startup_{{$k}}.conf
            mountPath: /etc/vpp/startup.conf
          - name: config-volume
            subPath: setup_{{$k}}.gate
            mountPath: /etc/vpp/setup.gate
          - name: vpp-sockets
            mountPath: {{ $.Values.volumeMounts.vpp_sockets.mountPath }}
      {{ end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "csp.fullname" . }}
            items:
            {{ range $k, $v := .Values.cnf }}
            - key: startup_{{$k}}.conf
              path: startup_{{$k}}.conf
            - key: setup_{{$k}}.gate
              path: setup_{{$k}}.gate
            {{ end }}
        - name: vpp-sockets
          hostPath:
            path: /etc/vpp/sockets/

