{{ $open5gsName := .Release.Name }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

nssf:
  sbi:
    - dev: "eth0"
      port: {{ .Values.containerPorts.sbi }}
      {{- if .Values.config.sbi.advertise }}
      advertise: "{{ tpl .Values.config.sbi.advertise . }}"
      {{- end }}
  nsi:
    {{- range .Values.config.nsiList }}
    - name: {{ default (printf "%s-nrf-sbi" $open5gsName) .nrf.hostname }}
      port: {{ .nrf.port }}
      s_nssai:
        sst: {{ .sst | quote }}
        {{- if .sd }}
        sd: {{ .sd | quote }}
        {{- end }}
    {{- end }}

nrf:
  sbi:
    - name: {{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}
      port: {{ .Values.config.nrf.sbi.port }}
