apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-privileged-operator-role
  namespace: simple-privileged-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
