apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simples.operator.tld
spec:
  group: operator.tld
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              replicas:
                type: integer
  scope: Namespaced
  names:
    plural: simples
    singular: simple
    kind: Simple
    shortNames:
    - sim
