vendor: MATRIXX Software
name: Matrixx Digital Commerce
version: 5270
website_url: www.matrixx.com
product_logo_url: https://www.dropbox.com/s/wrpx3vv1rkowg3h/matrixx_logo_software_color_cmyk.svg?dl=0
description: "The MATRIXX Digital Commerce Platform (DCP) is a cloud-native, real-time monetization engine delivering industry-compliant rating and charging functionality along with a rich array of digital commerce capabilities such as subscription management, event streaming and management, personalization, and digital payments."