---
apiVersion: v1
kind: Namespace
metadata:
  name: cnfspace
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-tini-sample
  namespace: cnfspace
spec:
  dnsPolicy: Default

  containers:
  - image: conformance/specialized-init:0.1
    name: nginx
    command: ["/tini", "--"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dumb-init-sample
  namespace: cnfspace
spec:
  dnsPolicy: Default

  containers:
  - image: conformance/specialized-init:0.1
    name: nginx-dumb-init
    command: ["/usr/bin/dumb-init", "--"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-s6-overlay-sample
  namespace: cnfspace
spec:
  dnsPolicy: Default

  containers:
  - image: conformance/specialized-init:0.1
    name: nginx-dumb-init
    command: ["/init"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80
