---
config_version: v2
common:
  container_names:
  - name: nginx
    rollback_from_tag: latest
    rolling_update_test_tag: latest
    rolling_downgrade_test_tag: latest
    rolling_version_change_test_tag: latest
deployments:
  manifests:
  - name: nginx
    manifest_directory: manifests
