---
helm_directory: chart
git_clone_url: 
install_script: chart
release_name: coredns
deployment_name: coredns-coredns 
deployment_label: k8s-app
service_name: coredns-coredns
application_deployment_names: [coredns]
helm_chart_container_name: coredns
container_names: 
  - name: coredns 
    rolling_update_test_tag: "1.8.0"
    rolling_downgrade_test_tag: 1.6.7
    rolling_version_change_test_tag: latest
    rollback_from_tag: latest
white_list_helm_chart_container_names: []
