nfvbench_macs: ['aa:bb:cc:dd:ee:ff','ff:ee:dd:cc:bb:aa']

privileged: true

replicaCount: 1

image:
  repository: soelvkaer/vppcontainer
  tag: latest
  pullPolicy: IfNotPresent

volumeMounts:
  vpp_sockets:
    mountPath: /root/sockets

## Configuration for 3c2n_csp
cnf:
  1:
    main_core: 8
    worker_cores: '14,42'
    sock: ['memif1','int11']
    memid: ['1','10']
    mac: ['52:54:00:00:00:aa','52:54:00:00:01:bb']
    owner: ['slave','master']
    queues: 1
    subnet: ['172.16.10.10/24','172.16.31.10/24']
    remip: ['172.16.10.100','172.16.31.11']
    remmac: ['{{ index .Values.nfvbench_macs 0 }}','52:54:00:00:02:aa']

  2:
    main_core: 10
    worker_cores: '16,44'
    sock: ['int11','memif2']
    memid: ['10','2']
    mac: ['52:54:00:00:02:aa','52:54:00:00:00:bb']
    owner: ['slave','slave']
    queues: 1
    subnet: ['172.16.31.11/24','172.16.20.10/24']
    remip: ['172.16.31.10','172.16.20.100']
    remmac: ['52:54:00:00:01:bb','{{ index .Values.nfvbench_macs 1 }}']

  3:
    main_core: 12
    worker_cores: '18,46'
    sock: ['memif3','int21']
    memid: ['3','10']
    mac: ['52:54:01:00:00:aa','52:54:01:00:01:bb']
    owner: ['slave','master']
    queues: 1
    subnet: ['172.16.10.11/24','172.16.31.10/24']
    remip: ['172.16.10.101','172.16.31.11']
    remmac: ['{{ index .Values.nfvbench_macs 0 }}','52:54:01:00:02:aa']

  4:
    main_core: 36
    worker_cores: '20,48'
    sock: ['int21','memif4']
    memid: ['10','4']
    mac: ['52:54:01:00:02:aa','52:54:01:00:00:bb']
    owner: ['slave','slave']
    queues: 1
    subnet: ['172.16.31.11/24','172.16.20.11/24']
    remip: ['172.16.31.10','172.16.20.101']
    remmac: ['52:54:01:00:01:bb','{{ index .Values.nfvbench_macs 1 }}']

  5:
    main_core: 38
    worker_cores: '22,50'
    sock: ['memif5','int31']
    memid: ['5','10']
    mac: ['52:54:02:00:00:aa','52:54:02:00:01:bb']
    owner: ['slave','master']
    queues: 1
    subnet: ['172.16.10.12/24','172.16.31.10/24']
    remip: ['172.16.10.102','172.16.31.11']
    remmac: ['{{ index .Values.nfvbench_macs 0 }}','52:54:02:00:02:aa']

  6:
    main_core: 40
    worker_cores: '24,52'
    sock: ['int31','memif6']
    memid: ['10','6']
    mac: ['52:54:02:00:02:aa','52:54:02:00:00:bb']
    owner: ['slave','slave']
    queues: 1
    subnet: ['172.16.31.11/24','172.16.20.12/24']
    remip: ['172.16.31.10','172.16.20.102']
    remmac: ['52:54:02:00:01:bb','{{ index .Values.nfvbench_macs 1 }}']
