apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: simple-privileged-operator
  namespace: default
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: simple-privileged-operator
  source: localhost:5001
  sourceNamespace: simple-privileged-operator
